= checkout github sources using git

This action is a replacement of standard github's `actions/checkout` action.
This action is implemented as `composite action`, so it does not require `node.js` interpreter.
The standard `actions/checkout` is written in `javascript` and sometimes it is not possible to have `node12` injected to the container.

= prerequisites

- `git` must be available. So, make sure `git` is installed before calling this action.

= step syntax

....
- name: <name>
  uses: myci-actions/checkout@<version>
  with:
    submodules: <true/false/remote/recursive/remote_recursive>
    path: <destination-directory>
    repository: <repository-URL>
....

arguments:

- `submodules` - Whether to clone submodules or not. Possible values: `true`= init submodules; `false` = do not init submodules; `remote` = init submodules and update them to the remote tracking branch; `recursive` = init submodules recursively; `remote_recursive` = init submodules recursively and update them to the remote tracking branch. Optional. Default value: `remote_recursive`.
- `path` - destination directory. Optional. Default value: `.`.
- `repository` - repository URL to clone. If empty then the current repository is cloned. Optional. Default value: empty.


Step example:
....
- name: checkout sources
  uses: myci-actions/checkout@10
....

